project:
  type: website
  output-dir: docs

website:
  title: "Biofísica de la Electroporación"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: 00_introduccion_membrana.qmd
        text: Membrana
      - href: 01_schwan_laplace.qmd
        text: Schwan
      - href: 02_dinamica_rc.qmd
        text: Circuito RC
      - href: 03_energia_poro.qmd
        text: Energía del poro
      - href: 04_calentamiento_joule.qmd
        text: Joule
      - href: 05_regimenes_operacion.qmd
        text: Regímenes
      - href: 06_tecnologia_electroporador.qmd
        text: Electroporador
      - href: 07_aplicaciones.qmd
        text: Aplicaciones
      - href: 08_actividades.qmd
        text: Actividades

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    smooth-scroll: true
    code-fold: true
    code-tools: true
    html-math-method: mathjax
    lang: es

bibliography: references.bib