<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Actividades de aprendizaje – Biofísica de la Electroporación</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Biofísica de la Electroporación</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./00_introduccion_membrana.html"> 
<span class="menu-text">Membrana</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01_schwan_laplace.html"> 
<span class="menu-text">Schwan</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02_dinamica_rc.html"> 
<span class="menu-text">Circuito RC</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03_energia_poro.html"> 
<span class="menu-text">Energía del poro</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./04_calentamiento_joule.html"> 
<span class="menu-text">Joule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./05_regimenes_operacion.html"> 
<span class="menu-text">Regímenes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06_tecnologia_electroporador.html"> 
<span class="menu-text">Electroporador</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./07_aplicaciones.html"> 
<span class="menu-text">Aplicaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./08_actividades.html" aria-current="page"> 
<span class="menu-text">Actividades</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#propósito-de-las-actividades" id="toc-propósito-de-las-actividades" class="nav-link active" data-scroll-target="#propósito-de-las-actividades"><span class="header-section-number">1</span> Propósito de las actividades</a></li>
  <li><a href="#cómo-enfrentar-estas-actividades" id="toc-cómo-enfrentar-estas-actividades" class="nav-link" data-scroll-target="#cómo-enfrentar-estas-actividades"><span class="header-section-number">2</span> Cómo enfrentar estas actividades</a></li>
  <li><a href="#actividad-1-voltaje-transmembrana-inducido" id="toc-actividad-1-voltaje-transmembrana-inducido" class="nav-link" data-scroll-target="#actividad-1-voltaje-transmembrana-inducido"><span class="header-section-number">3</span> Actividad 1: voltaje transmembrana inducido</a>
  <ul class="collapse">
  <li><a href="#objetivo" id="toc-objetivo" class="nav-link" data-scroll-target="#objetivo"><span class="header-section-number">3.1</span> Objetivo</a></li>
  <li><a href="#contexto-físico" id="toc-contexto-físico" class="nav-link" data-scroll-target="#contexto-físico"><span class="header-section-number">3.2</span> Contexto físico</a></li>
  <li><a href="#procedimiento" id="toc-procedimiento" class="nav-link" data-scroll-target="#procedimiento"><span class="header-section-number">3.3</span> Procedimiento</a></li>
  <li><a href="#preguntas-orientadoras" id="toc-preguntas-orientadoras" class="nav-link" data-scroll-target="#preguntas-orientadoras"><span class="header-section-number">3.4</span> Preguntas orientadoras</a></li>
  </ul></li>
  <li><a href="#actividad-2-carga-temporal-de-la-membrana" id="toc-actividad-2-carga-temporal-de-la-membrana" class="nav-link" data-scroll-target="#actividad-2-carga-temporal-de-la-membrana"><span class="header-section-number">4</span> Actividad 2: carga temporal de la membrana</a>
  <ul class="collapse">
  <li><a href="#objetivo-1" id="toc-objetivo-1" class="nav-link" data-scroll-target="#objetivo-1"><span class="header-section-number">4.1</span> Objetivo</a></li>
  <li><a href="#contexto-físico-1" id="toc-contexto-físico-1" class="nav-link" data-scroll-target="#contexto-físico-1"><span class="header-section-number">4.2</span> Contexto físico</a></li>
  <li><a href="#procedimiento-1" id="toc-procedimiento-1" class="nav-link" data-scroll-target="#procedimiento-1"><span class="header-section-number">4.3</span> Procedimiento</a></li>
  <li><a href="#preguntas-orientadoras-1" id="toc-preguntas-orientadoras-1" class="nav-link" data-scroll-target="#preguntas-orientadoras-1"><span class="header-section-number">4.4</span> Preguntas orientadoras</a></li>
  </ul></li>
  <li><a href="#actividad-3-energía-libre-de-formación-del-poro" id="toc-actividad-3-energía-libre-de-formación-del-poro" class="nav-link" data-scroll-target="#actividad-3-energía-libre-de-formación-del-poro"><span class="header-section-number">5</span> Actividad 3: energía libre de formación del poro</a>
  <ul class="collapse">
  <li><a href="#objetivo-2" id="toc-objetivo-2" class="nav-link" data-scroll-target="#objetivo-2"><span class="header-section-number">5.1</span> Objetivo</a></li>
  <li><a href="#contexto-físico-2" id="toc-contexto-físico-2" class="nav-link" data-scroll-target="#contexto-físico-2"><span class="header-section-number">5.2</span> Contexto físico</a></li>
  <li><a href="#procedimiento-2" id="toc-procedimiento-2" class="nav-link" data-scroll-target="#procedimiento-2"><span class="header-section-number">5.3</span> Procedimiento</a></li>
  <li><a href="#preguntas-orientadoras-2" id="toc-preguntas-orientadoras-2" class="nav-link" data-scroll-target="#preguntas-orientadoras-2"><span class="header-section-number">5.4</span> Preguntas orientadoras</a></li>
  </ul></li>
  <li><a href="#actividad-4-calentamiento-joule" id="toc-actividad-4-calentamiento-joule" class="nav-link" data-scroll-target="#actividad-4-calentamiento-joule"><span class="header-section-number">6</span> Actividad 4: calentamiento Joule</a>
  <ul class="collapse">
  <li><a href="#objetivo-3" id="toc-objetivo-3" class="nav-link" data-scroll-target="#objetivo-3"><span class="header-section-number">6.1</span> Objetivo</a></li>
  <li><a href="#contexto-físico-3" id="toc-contexto-físico-3" class="nav-link" data-scroll-target="#contexto-físico-3"><span class="header-section-number">6.2</span> Contexto físico</a></li>
  <li><a href="#procedimiento-3" id="toc-procedimiento-3" class="nav-link" data-scroll-target="#procedimiento-3"><span class="header-section-number">6.3</span> Procedimiento</a></li>
  <li><a href="#preguntas-orientadoras-3" id="toc-preguntas-orientadoras-3" class="nav-link" data-scroll-target="#preguntas-orientadoras-3"><span class="header-section-number">6.4</span> Preguntas orientadoras</a></li>
  </ul></li>
  <li><a href="#actividad-integradora" id="toc-actividad-integradora" class="nav-link" data-scroll-target="#actividad-integradora"><span class="header-section-number">7</span> Actividad integradora</a>
  <ul class="collapse">
  <li><a href="#objetivo-4" id="toc-objetivo-4" class="nav-link" data-scroll-target="#objetivo-4"><span class="header-section-number">7.1</span> Objetivo</a></li>
  <li><a href="#situación-problema" id="toc-situación-problema" class="nav-link" data-scroll-target="#situación-problema"><span class="header-section-number">7.2</span> Situación problema</a></li>
  <li><a href="#preguntas-orientadoras-4" id="toc-preguntas-orientadoras-4" class="nav-link" data-scroll-target="#preguntas-orientadoras-4"><span class="header-section-number">7.3</span> Preguntas orientadoras</a></li>
  </ul></li>
  <li><a href="#cierre" id="toc-cierre" class="nav-link" data-scroll-target="#cierre"><span class="header-section-number">8</span> Cierre</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Actividades de aprendizaje</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="propósito-de-las-actividades" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Propósito de las actividades</h1>
<p>Las siguientes actividades están diseñadas para reforzar los conceptos biofísicos centrales de la electroporación mediante análisis cuantitativo, interpretación gráfica y razonamiento físico.</p>
<p>El objetivo no es memorizar ecuaciones, sino comprender cómo el campo eléctrico externo, el tamaño celular, la dinámica capacitiva de la membrana, la energía libre de formación de poros y la disipación Joule se relacionan entre sí.</p>
</section>
<section id="cómo-enfrentar-estas-actividades" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Cómo enfrentar estas actividades</h1>
<p>Antes de abrir cualquier pista o respuesta, se recomienda seguir este orden de trabajo:</p>
<p><strong>Paso 1 — Lee el enunciado completo</strong> sin abrir nada. Identifica qué se pregunta, qué datos tienes y qué ecuación podría ser relevante.</p>
<p><strong>Paso 2 — Intenta resolverlo por tu cuenta</strong> durante al menos 10 minutos. Escribe en papel las unidades de cada variable. Los errores más frecuentes en estas actividades son de conversión de unidades, no de conceptos.</p>
<p><strong>Paso 3 — Si estás bloqueado, abre la pista.</strong> La pista no da la respuesta: da una orientación sobre cómo empezar o qué verificar. Úsala como un empuje, no como un atajo.</p>
<p><strong>Paso 4 — Después de obtener tu resultado, abre la respuesta</strong> para comparar. Si tu número coincide, verifica también la interpretación física. Si no coincide, busca el paso donde difieren antes de leer la solución completa.</p>
<p><strong>Paso 5 — Escribe con tus propias palabras</strong> qué aprendiste de esa actividad. Una frase es suficiente.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Sobre las respuestas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las respuestas incluyen el desarrollo completo y la interpretación física. No están ahí para copiarse, sino para que puedas identificar exactamente dónde razonaste diferente. El valor está en ese proceso de comparación, no en el número final.</p>
</div>
</div>
<hr>
</section>
<section id="actividad-1-voltaje-transmembrana-inducido" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Actividad 1: voltaje transmembrana inducido</h1>
<p><em>Nivel: básico</em></p>
<section id="objetivo" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="objetivo"><span class="header-section-number">3.1</span> Objetivo</h2>
<p>Estimar el voltaje transmembrana inducido por un campo eléctrico externo y analizar en qué condiciones se puede alcanzar un umbral aproximado de electroporación.</p>
</section>
<section id="contexto-físico" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="contexto-físico"><span class="header-section-number">3.2</span> Contexto físico</h2>
<p>Para una célula aproximadamente esférica, el voltaje transmembrana inducido puede estimarse mediante la ecuación de Schwan:</p>
<p><span class="math display">\[
\Delta V_m^{\mathrm{ind}}(\theta)
=
1.5\,a\,E_0\cos\theta
\]</span></p>
<p>donde <span class="math inline">\(a\)</span> es el radio celular, <span class="math inline">\(E_0\)</span> el campo eléctrico externo y <span class="math inline">\(\theta\)</span> el ángulo medido respecto a la dirección del campo. En los polos (<span class="math inline">\(\theta = 0\)</span>, <span class="math inline">\(\cos\theta = 1\)</span>):</p>
<p><span class="math display">\[
\Delta V_m^{\mathrm{ind}}
=
1.5\,a\,E_0
\]</span></p>
</section>
<section id="procedimiento" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="procedimiento"><span class="header-section-number">3.3</span> Procedimiento</h2>
<p>Considere una célula de radio <span class="math inline">\(a = 10~\mu\mathrm{m}\)</span>. Calcule <span class="math inline">\(\Delta V_m^{\mathrm{ind}}\)</span> en los polos para los siguientes campos eléctricos y complete la tabla:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Caso</th>
<th><span class="math inline">\(E_0\)</span></th>
<th><span class="math inline">\(\Delta V_m^{\mathrm{ind}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(0.2~\mathrm{kV/cm}\)</span></td>
<td>?</td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(0.5~\mathrm{kV/cm}\)</span></td>
<td>?</td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(1.0~\mathrm{kV/cm}\)</span></td>
<td>?</td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(1.5~\mathrm{kV/cm}\)</span></td>
<td>?</td>
</tr>
<tr class="odd">
<td>5</td>
<td><span class="math inline">\(2.0~\mathrm{kV/cm}\)</span></td>
<td>?</td>
</tr>
</tbody>
</table>
</section>
<section id="preguntas-orientadoras" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="preguntas-orientadoras"><span class="header-section-number">3.4</span> Preguntas orientadoras</h2>
<ol type="1">
<li>¿Para qué valores de <span class="math inline">\(E_0\)</span> se supera aproximadamente <span class="math inline">\(\Delta V_m^{\mathrm{ind}} = 1~\mathrm{V}\)</span>?</li>
<li>¿Por qué una célula más grande alcanza un mayor voltaje inducido bajo el mismo campo?</li>
<li>¿Qué ocurriría si el radio celular fuera <span class="math inline">\(5~\mu\mathrm{m}\)</span> en lugar de <span class="math inline">\(10~\mu\mathrm{m}\)</span>?</li>
<li>¿Por qué el voltaje inducido es máximo en los polos y nulo cerca del ecuador?</li>
<li>¿Qué limitaciones tiene usar esta ecuación como criterio directo de electroporación?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Pista — Actividad 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La clave está en las unidades. La ecuación usa metros y V/m, pero los datos están en <span class="math inline">\(\mu\)</span>m y kV/cm. Antes de sustituir, convierte todo al SI:</p>
<p><span class="math display">\[
1~\mu\mathrm{m} = 10^{-6}~\mathrm{m}
\qquad
1~\mathrm{kV/cm} = \frac{10^3~\mathrm{V}}{10^{-2}~\mathrm{m}} = 10^5~\mathrm{V/m}
\]</span></p>
<p>Después la ecuación es directa: multiplica <span class="math inline">\(1.5 \times a \times E_0\)</span>. El resultado debe quedar en voltios.</p>
<p>Para las preguntas conceptuales: la ecuación de Schwan es lineal tanto en <span class="math inline">\(a\)</span> como en <span class="math inline">\(E_0\)</span>. Eso significa que si duplicas el radio, el voltaje se duplica; si duplicas el campo, también se duplica. Y <span class="math inline">\(\cos\theta\)</span> vale 1 en los polos y 0 en el ecuador.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>✓ Respuesta — Actividad 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Conversión de unidades:</strong></p>
<p><span class="math display">\[
a = 10~\mu\mathrm{m} = 10 \times 10^{-6}~\mathrm{m} = 10^{-5}~\mathrm{m}
\qquad
1~\mathrm{kV/cm} = 10^5~\mathrm{V/m}
\]</span></p>
<p><strong>Tabla de resultados:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th><span class="math inline">\(E_0\)</span></th>
<th><span class="math inline">\(E_0\)</span> [V/m]</th>
<th><span class="math inline">\(\Delta V_m^{\mathrm{ind}} = 1.5 \times 10^{-5} \times E_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(0.2~\mathrm{kV/cm}\)</span></td>
<td><span class="math inline">\(2.0\times10^4\)</span></td>
<td><span class="math inline">\(0.300~\mathrm{V}\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(0.5~\mathrm{kV/cm}\)</span></td>
<td><span class="math inline">\(5.0\times10^4\)</span></td>
<td><span class="math inline">\(0.750~\mathrm{V}\)</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(1.0~\mathrm{kV/cm}\)</span></td>
<td><span class="math inline">\(1.0\times10^5\)</span></td>
<td><span class="math inline">\(1.500~\mathrm{V}\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(1.5~\mathrm{kV/cm}\)</span></td>
<td><span class="math inline">\(1.5\times10^5\)</span></td>
<td><span class="math inline">\(2.250~\mathrm{V}\)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td><span class="math inline">\(2.0~\mathrm{kV/cm}\)</span></td>
<td><span class="math inline">\(2.0\times10^5\)</span></td>
<td><span class="math inline">\(3.000~\mathrm{V}\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Interpretación:</strong></p>
<ol type="1">
<li><p>El umbral de <span class="math inline">\(1~\mathrm{V}\)</span> se supera a partir de <span class="math inline">\(E_0 = 1.0~\mathrm{kV/cm}\)</span> (casos 3, 4 y 5).</p></li>
<li><p>La ecuación es lineal en <span class="math inline">\(a\)</span>: <span class="math inline">\(\Delta V_m^{\mathrm{ind}} \propto a\)</span>. Una célula más grande presenta más separación entre sus polos bajo el mismo campo externo y acumula más diferencia de potencial.</p></li>
<li><p>Si <span class="math inline">\(a = 5~\mu\mathrm{m}\)</span>, todos los voltajes se reducirían a la mitad. Para superar <span class="math inline">\(1~\mathrm{V}\)</span> habría que aplicar <span class="math inline">\(E_0 = 2.0~\mathrm{kV/cm}\)</span>.</p></li>
<li><p>El factor <span class="math inline">\(\cos\theta\)</span> es máximo en <span class="math inline">\(\theta = 0\)</span> (polo alineado con el campo) y se anula en <span class="math inline">\(\theta = \pi/2\)</span> (ecuador). Esto refleja la geometría de la polarización dipolar inducida por el campo externo.</p></li>
<li><p>Limitaciones principales: la ecuación asume estado cuasiestático, célula perfectamente esférica, membrana sin conductancia, campo uniforme y ausencia de interacciones entre células. La electroporación también depende de la duración del pulso y de la barrera energética del poro.</p></li>
</ol>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="actividad-2-carga-temporal-de-la-membrana" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Actividad 2: carga temporal de la membrana</h1>
<p><em>Nivel: básico</em></p>
<section id="objetivo-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="objetivo-1"><span class="header-section-number">4.1</span> Objetivo</h2>
<p>Analizar cómo la duración del pulso afecta la carga capacitiva de la membrana y el valor máximo alcanzado por el voltaje transmembrana inducido.</p>
</section>
<section id="contexto-físico-1" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="contexto-físico-1"><span class="header-section-number">4.2</span> Contexto físico</h2>
<p>Durante un pulso rectangular que comienza en <span class="math inline">\(t_0\)</span>, la componente inducida del voltaje transmembrana evoluciona como:</p>
<p><span class="math display">\[
\Delta V_m^{\mathrm{ind}}(t)
=
\Delta V_{m,\max}^{\mathrm{ind}}
\left(1-e^{-(t-t_0)/\tau_m}\right)
\qquad
t_0 \leq t \leq t_0 + t_p
\]</span></p>
<p>Al final del pulso:</p>
<p><span class="math display">\[
\Delta V_m^{\mathrm{ind}}(t_0 + t_p)
=
\Delta V_{m,\max}^{\mathrm{ind}}
\left(1-e^{-t_p/\tau_m}\right)
\]</span></p>
</section>
<section id="procedimiento-1" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="procedimiento-1"><span class="header-section-number">4.3</span> Procedimiento</h2>
<p>Suponga <span class="math inline">\(\Delta V_{m,\max}^{\mathrm{ind}} = 1.5~\mathrm{V}\)</span> y <span class="math inline">\(\tau_m = 1~\mu\mathrm{s}\)</span>. Calcule el voltaje alcanzado al final del pulso y la fracción respecto al máximo para cada caso:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th><span class="math inline">\(t_p\)</span></th>
<th><span class="math inline">\(\Delta V_m^{\mathrm{ind}}(t_0 + t_p)\)</span></th>
<th>Fracción del máximo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(100~\mathrm{ns}\)</span></td>
<td>?</td>
<td>?</td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(10~\mu\mathrm{s}\)</span></td>
<td>?</td>
<td>?</td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(1~\mathrm{ms}\)</span></td>
<td>?</td>
<td>?</td>
</tr>
</tbody>
</table>
</section>
<section id="preguntas-orientadoras-1" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="preguntas-orientadoras-1"><span class="header-section-number">4.4</span> Preguntas orientadoras</h2>
<ol type="1">
<li>¿Qué fracción de <span class="math inline">\(\Delta V_{m,\max}^{\mathrm{ind}}\)</span> se alcanza en cada caso?</li>
<li>¿Cuál de los tres pulsos permite que la membrana se cargue casi completamente?</li>
<li>¿Por qué un pulso de <span class="math inline">\(100~\mathrm{ns}\)</span> puede no permitir que la membrana alcance el valor esperado por la ecuación de Schwan?</li>
<li>¿Por qué los pulsos más cortos pueden requerir campos eléctricos mayores?</li>
<li>¿Qué diferencia conceptual hay entre aplicar un campo intenso durante nanosegundos y uno menor durante microsegundos?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Pista — Actividad 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La clave es comparar <span class="math inline">\(t_p\)</span> con <span class="math inline">\(\tau_m = 1~\mu\mathrm{s}\)</span>. La fracción de carga alcanzada depende del cociente <span class="math inline">\(t_p / \tau_m\)</span>:</p>
<ul>
<li>Si <span class="math inline">\(t_p \ll \tau_m\)</span>: el exponencial apenas decae, la membrana se carga muy poco.</li>
<li>Si <span class="math inline">\(t_p \approx \tau_m\)</span>: la membrana alcanza <span class="math inline">\(1 - e^{-1} \approx 63\%\)</span> del máximo.</li>
<li>Si <span class="math inline">\(t_p \gg \tau_m\)</span>: el exponencial se acerca a cero, la membrana alcanza casi el <span class="math inline">\(100\%\)</span>.</li>
</ul>
<p>Convierte las duraciones al SI antes de calcular:</p>
<p><span class="math display">\[
100~\mathrm{ns} = 10^{-7}~\mathrm{s}
\qquad
10~\mu\mathrm{s} = 10^{-5}~\mathrm{s}
\qquad
1~\mathrm{ms} = 10^{-3}~\mathrm{s}
\qquad
\tau_m = 10^{-6}~\mathrm{s}
\]</span></p>
<p>Calcula primero el cociente <span class="math inline">\(t_p/\tau_m\)</span>, luego evalúa <span class="math inline">\(1 - e^{-t_p/\tau_m}\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>✓ Respuesta — Actividad 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Expresión a evaluar:</strong></p>
<p><span class="math display">\[
\Delta V_m^{\mathrm{ind}}(t_0 + t_p)
=
1.5 \times \left(1 - e^{-t_p/\tau_m}\right)~\mathrm{V}
\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th><span class="math inline">\(t_p\)</span></th>
<th><span class="math inline">\(t_p/\tau_m\)</span></th>
<th><span class="math inline">\(1 - e^{-t_p/\tau_m}\)</span></th>
<th>Voltaje alcanzado</th>
<th>Fracción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(100~\mathrm{ns}\)</span></td>
<td><span class="math inline">\(0.1\)</span></td>
<td><span class="math inline">\(0.0952\)</span></td>
<td><span class="math inline">\(0.143~\mathrm{V}\)</span></td>
<td><span class="math inline">\(9.5\%\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(10~\mu\mathrm{s}\)</span></td>
<td><span class="math inline">\(10\)</span></td>
<td><span class="math inline">\(\approx 1.000\)</span></td>
<td><span class="math inline">\(\approx 1.500~\mathrm{V}\)</span></td>
<td><span class="math inline">\(\approx 100\%\)</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(1~\mathrm{ms}\)</span></td>
<td><span class="math inline">\(1000\)</span></td>
<td><span class="math inline">\(\approx 1.000\)</span></td>
<td><span class="math inline">\(\approx 1.500~\mathrm{V}\)</span></td>
<td><span class="math inline">\(\approx 100\%\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Interpretación:</strong></p>
<ol type="1">
<li><p>El pulso de <span class="math inline">\(100~\mathrm{ns}\)</span> solo carga la membrana hasta el <span class="math inline">\(9.5\%\)</span> del valor máximo. Los pulsos de <span class="math inline">\(10~\mu\mathrm{s}\)</span> y <span class="math inline">\(1~\mathrm{ms}\)</span> la cargan prácticamente al <span class="math inline">\(100\%\)</span>, ya que <span class="math inline">\(t_p \gg \tau_m\)</span>.</p></li>
<li><p>Los casos 2 y 3 permiten alcanzar la carga completa.</p></li>
<li><p>La ecuación de Schwan describe el voltaje en estado cuasiestático (para <span class="math inline">\(t_p \gg \tau_m\)</span>). Un pulso de <span class="math inline">\(100~\mathrm{ns}\)</span> es mucho más corto que <span class="math inline">\(\tau_m\)</span>, por lo que la membrana no tiene tiempo de cargarse hasta ese valor.</p></li>
<li><p>Si el pulso es corto, la membrana solo alcanza una fracción pequeña del voltaje máximo. Para compensar y llegar al mismo voltaje absoluto habría que aumentar <span class="math inline">\(\Delta V_{m,\max}^{\mathrm{ind}} = 1.5\,a\,E_0\)</span>, es decir, aumentar el campo <span class="math inline">\(E_0\)</span>.</p></li>
<li><p>Un campo intenso durante nanosegundos puede penetrar al interior celular sin cargar la membrana significativamente (pulsos nanosegundo o nsPEF). Un campo menor durante microsegundos o milisegundos carga completamente la membrana y produce permeabilización clásica de la bicapa lipídica.</p></li>
</ol>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="actividad-3-energía-libre-de-formación-del-poro" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Actividad 3: energía libre de formación del poro</h1>
<p><em>Nivel: medio</em></p>
<section id="objetivo-2" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="objetivo-2"><span class="header-section-number">5.1</span> Objetivo</h2>
<p>Interpretar cómo el voltaje transmembrana total modifica el paisaje de energía libre asociado a la formación de un poro de membrana.</p>
</section>
<section id="contexto-físico-2" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="contexto-físico-2"><span class="header-section-number">5.2</span> Contexto físico</h2>
<p>El modelo simplificado para la energía libre de un poro de radio <span class="math inline">\(r\)</span> es:</p>
<p><span class="math display">\[
\Delta G(r,V_m^{\mathrm{tot}})
\approx
2\pi r\gamma
-
\pi r^2\Gamma
-
k r^2\left(V_m^{\mathrm{tot}}\right)^2
\]</span></p>
<p>El radio crítico y la barrera energética se obtienen del máximo de <span class="math inline">\(\Delta G(r)\)</span>:</p>
<p><span class="math display">\[
r_c
=
\frac{\pi\gamma}{\pi\Gamma+k\left(V_m^{\mathrm{tot}}\right)^2}
\qquad
\Delta G_c
=
\frac{\pi^2\gamma^2}{\pi\Gamma+k\left(V_m^{\mathrm{tot}}\right)^2}
\]</span></p>
</section>
<section id="procedimiento-2" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="procedimiento-2"><span class="header-section-number">5.3</span> Procedimiento</h2>
<p>Use los parámetros físicos justificados en el módulo correspondiente:</p>
<p><span class="math display">\[
\gamma = 9.2~\mathrm{pN}
\qquad
\Gamma = 1~\mathrm{mN/m}
\qquad
k = 556~\mathrm{mF/m^2}
\qquad
T = 298~\mathrm{K}
\]</span></p>
<p>Calcule <span class="math inline">\(r_c\)</span> y <span class="math inline">\(\Delta G_c\)</span> (en unidades de <span class="math inline">\(k_BT\)</span>) para cada voltaje:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Caso</th>
<th><span class="math inline">\(V_m^{\mathrm{tot}}\)</span></th>
<th><span class="math inline">\(r_c\)</span></th>
<th><span class="math inline">\(\Delta G_c\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(0~\mathrm{mV}\)</span></td>
<td>?</td>
<td>?</td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(150~\mathrm{mV}\)</span></td>
<td>?</td>
<td>?</td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(300~\mathrm{mV}\)</span></td>
<td>?</td>
<td>?</td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(450~\mathrm{mV}\)</span></td>
<td>?</td>
<td>?</td>
</tr>
<tr class="odd">
<td>5</td>
<td><span class="math inline">\(600~\mathrm{mV}\)</span></td>
<td>?</td>
<td>?</td>
</tr>
</tbody>
</table>
</section>
<section id="preguntas-orientadoras-2" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="preguntas-orientadoras-2"><span class="header-section-number">5.4</span> Preguntas orientadoras</h2>
<ol type="1">
<li>¿Cómo cambian <span class="math inline">\(r_c\)</span> y <span class="math inline">\(\Delta G_c\)</span> al aumentar <span class="math inline">\(V_m^{\mathrm{tot}}\)</span>?</li>
<li>¿Por qué el voltaje aparece elevado al cuadrado en el término eléctrico?</li>
<li>¿Qué significa físicamente que la barrera <span class="math inline">\(\Delta G_c\)</span> disminuya?</li>
<li>¿Por qué una barrera menor no implica ruptura irreversible inmediata?</li>
<li>¿A partir de qué voltaje la barrera cae por debajo de <span class="math inline">\(\sim 5\,k_BT\)</span>?</li>
<li>¿Qué diferencias conceptuales hay entre nucleación, expansión y daño irreversible?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Pista — Actividad 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Primero convierte todo al SI:</p>
<p><span class="math display">\[
\gamma = 9.2 \times 10^{-12}~\mathrm{J/m}
\qquad
\Gamma = 10^{-3}~\mathrm{J/m^2}
\qquad
k = 0.556~\mathrm{F/m^2}
\]</span></p>
<p><span class="math display">\[
k_BT = 1.381 \times 10^{-23} \times 298 \approx 4.114 \times 10^{-21}~\mathrm{J}
\]</span></p>
<p>Los voltajes también en V: <span class="math inline">\(150~\mathrm{mV} = 0.150~\mathrm{V}\)</span>, etc.</p>
<p>Calcula primero el denominador <span class="math inline">\(A = \pi\Gamma + k V^2\)</span> para cada voltaje. Luego:</p>
<p><span class="math display">\[
r_c = \frac{\pi\gamma}{A}~\mathrm{[m]}
\quad\rightarrow\quad
r_c~\mathrm{[nm]} = r_c~\mathrm{[m]} \times 10^9
\]</span></p>
<p><span class="math display">\[
\Delta G_c = \frac{\pi^2\gamma^2}{A}~\mathrm{[J]}
\quad\rightarrow\quad
\Delta G_c~[k_BT] = \frac{\Delta G_c~\mathrm{[J]}}{k_BT}
\]</span></p>
<p>Observa cómo <span class="math inline">\(A\)</span> crece con <span class="math inline">\(V^2\)</span>: a mayor voltaje, mayor denominador, y por tanto menor <span class="math inline">\(r_c\)</span> y menor <span class="math inline">\(\Delta G_c\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>✓ Respuesta — Actividad 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Parámetros en SI:</strong></p>
<p><span class="math display">\[
\gamma = 9.2 \times 10^{-12}~\mathrm{J/m}
\qquad
\Gamma = 10^{-3}~\mathrm{J/m^2}
\qquad
k = 0.556~\mathrm{F/m^2}
\qquad
k_BT = 4.114 \times 10^{-21}~\mathrm{J}
\]</span></p>
<p><strong>Denominador:</strong> <span class="math inline">\(A = \pi\Gamma + k V^2\)</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th><span class="math inline">\(V_m^{\mathrm{tot}}\)</span></th>
<th><span class="math inline">\(A~\mathrm{[J/m^2]}\)</span></th>
<th><span class="math inline">\(r_c~\mathrm{[nm]}\)</span></th>
<th><span class="math inline">\(\Delta G_c~[k_BT]\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(0~\mathrm{mV}\)</span></td>
<td><span class="math inline">\(3.14 \times 10^{-3}\)</span></td>
<td><span class="math inline">\(9.20\)</span></td>
<td><span class="math inline">\(64.6\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(150~\mathrm{mV}\)</span></td>
<td><span class="math inline">\(1.566 \times 10^{-2}\)</span></td>
<td><span class="math inline">\(1.847\)</span></td>
<td><span class="math inline">\(13.0\)</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(300~\mathrm{mV}\)</span></td>
<td><span class="math inline">\(5.135 \times 10^{-2}\)</span></td>
<td><span class="math inline">\(0.544\)</span></td>
<td><span class="math inline">\(3.82\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(450~\mathrm{mV}\)</span></td>
<td><span class="math inline">\(1.128 \times 10^{-1}\)</span></td>
<td><span class="math inline">\(0.250\)</span></td>
<td><span class="math inline">\(1.75\)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td><span class="math inline">\(600~\mathrm{mV}\)</span></td>
<td><span class="math inline">\(2.003 \times 10^{-1}\)</span></td>
<td><span class="math inline">\(0.142\)</span></td>
<td><span class="math inline">\(1.00\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Interpretación:</strong></p>
<ol type="1">
<li><p>Al aumentar <span class="math inline">\(V_m^{\mathrm{tot}}\)</span>, tanto <span class="math inline">\(r_c\)</span> como <span class="math inline">\(\Delta G_c\)</span> disminuyen progresivamente, porque el término <span class="math inline">\(kV^2\)</span> crece y aumenta el denominador <span class="math inline">\(A\)</span>.</p></li>
<li><p>El término eléctrico es <span class="math inline">\(-kr^2V^2\)</span>. La energía almacenada en un campo eléctrico es proporcional a <span class="math inline">\(V^2\)</span> (como en un condensador). El efecto no depende del signo del voltaje, solo de su magnitud al cuadrado.</p></li>
<li><p>Una barrera <span class="math inline">\(\Delta G_c\)</span> menor significa que las fluctuaciones térmicas tienen mayor probabilidad de superarla y nuclearse. Cuanto más baja la barrera, más probable la formación espontánea de poros.</p></li>
<li><p>La superación de la barrera de nucleación abre el poro hidrofílico, pero la expansión posterior depende de si el campo y la tensión superficial favorecen el crecimiento. Un poro puede nuclearse y luego cerrarse si la energía para expandirse sigue siendo desfavorable.</p></li>
<li><p>Entre <span class="math inline">\(V = 300~\mathrm{mV}\)</span> y <span class="math inline">\(V = 150~\mathrm{mV}\)</span>: a <span class="math inline">\(300~\mathrm{mV}\)</span> la barrera ya es <span class="math inline">\(3.82\,k_BT\)</span>, claramente por debajo de <span class="math inline">\(5\,k_BT\)</span>. A <span class="math inline">\(150~\mathrm{mV}\)</span> es <span class="math inline">\(13.0\,k_BT\)</span>, aún alta. Por tanto, el umbral de <span class="math inline">\(5\,k_BT\)</span> se cruza entre <span class="math inline">\(150~\mathrm{mV}\)</span> y <span class="math inline">\(300~\mathrm{mV}\)</span>.</p></li>
<li><p><strong>Nucleación</strong>: formación del primer poro hidrofílico estable (superar <span class="math inline">\(\Delta G_c\)</span>). <strong>Expansión</strong>: crecimiento del radio una vez nucleado. <strong>Daño irreversible</strong>: expansión tan grande que la membrana no recupera su integridad (requiere superar la barrera de ruptura, que es mucho mayor a voltajes bajos, <span class="math inline">\(\sim 300\,k_BT\)</span>).</p></li>
</ol>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="actividad-4-calentamiento-joule" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Actividad 4: calentamiento Joule</h1>
<p><em>Nivel: medio</em></p>
<section id="objetivo-3" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="objetivo-3"><span class="header-section-number">6.1</span> Objetivo</h2>
<p>Estimar el aumento de temperatura producido por disipación Joule durante un pulso eléctrico y discutir cuándo el calentamiento puede dejar de ser despreciable.</p>
</section>
<section id="contexto-físico-3" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="contexto-físico-3"><span class="header-section-number">6.2</span> Contexto físico</h2>
<p>La potencia volumétrica disipada en un medio conductor es:</p>
<p><span class="math display">\[
q = \sigma E^2
\]</span></p>
<p>Para un pulso corto, bajo aproximación adiabática:</p>
<p><span class="math display">\[
\Delta T
\approx
\frac{\sigma E^2\tau}{\rho c_p}
\]</span></p>
<p>donde <span class="math inline">\(\sigma\)</span> es la conductividad, <span class="math inline">\(E\)</span> el campo eléctrico, <span class="math inline">\(\tau\)</span> la duración del pulso, <span class="math inline">\(\rho\)</span> la densidad y <span class="math inline">\(c_p\)</span> el calor específico.</p>
</section>
<section id="procedimiento-3" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="procedimiento-3"><span class="header-section-number">6.3</span> Procedimiento</h2>
<p>Use <span class="math inline">\(\rho = 1000~\mathrm{kg\,m^{-3}}\)</span> y <span class="math inline">\(c_p = 4180~\mathrm{J\,kg^{-1}\,K^{-1}}\)</span>. Recuerde que <span class="math inline">\(1~\mathrm{kV/cm} = 10^5~\mathrm{V/m}\)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th style="text-align: right;"><span class="math inline">\(\sigma~\mathrm{[S/m]}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(E~\mathrm{[kV/cm]}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\tau\)</span></th>
<th><span class="math inline">\(\Delta T~\mathrm{[K]}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;"><span class="math inline">\(100~\mu\mathrm{s}\)</span></td>
<td>?</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;"><span class="math inline">\(100~\mu\mathrm{s}\)</span></td>
<td>?</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;"><span class="math inline">\(100~\mu\mathrm{s}\)</span></td>
<td>?</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;"><span class="math inline">\(100~\mu\mathrm{s}\)</span></td>
<td>?</td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;"><span class="math inline">\(1~\mathrm{ms}\)</span></td>
<td>?</td>
</tr>
<tr class="even">
<td>6</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;"><span class="math inline">\(1~\mathrm{ms}\)</span></td>
<td>?</td>
</tr>
</tbody>
</table>
</section>
<section id="preguntas-orientadoras-3" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="preguntas-orientadoras-3"><span class="header-section-number">6.4</span> Preguntas orientadoras</h2>
<ol type="1">
<li>¿Cuál de los casos produce el mayor calentamiento?</li>
<li>¿Qué variable tiene mayor efecto sobre <span class="math inline">\(\Delta T\)</span>: duplicar <span class="math inline">\(E\)</span>, <span class="math inline">\(\sigma\)</span> o <span class="math inline">\(\tau\)</span>?</li>
<li>¿Por qué el campo eléctrico tiene un efecto cuadrático sobre el calentamiento?</li>
<li>¿En qué casos el calentamiento podría ser biológicamente relevante?</li>
<li>¿Por qué esta estimación no reemplaza un modelo completo de transferencia de calor?</li>
<li>¿Cómo cambiaría <span class="math inline">\(\Delta T\)</span> con un tren de muchos pulsos?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Pista — Actividad 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La ecuación <span class="math inline">\(\Delta T = \sigma E^2 \tau / (\rho c_p)\)</span> tiene tres variables independientes. Antes de calcular, piensa cualitativamente qué ocurre al duplicar cada una:</p>
<ul>
<li>Duplicar <span class="math inline">\(\sigma\)</span>: <span class="math inline">\(\Delta T\)</span> se <strong>duplica</strong> (efecto lineal).</li>
<li>Duplicar <span class="math inline">\(\tau\)</span>: <span class="math inline">\(\Delta T\)</span> se <strong>duplica</strong> (efecto lineal).</li>
<li>Duplicar <span class="math inline">\(E\)</span>: <span class="math inline">\(\Delta T\)</span> se <strong>cuadruplica</strong> (efecto cuadrático, ya que <span class="math inline">\(E\)</span> aparece como <span class="math inline">\(E^2\)</span>).</li>
</ul>
<p>Usa esto para predecir los casos 3 y 4 a partir del caso 2 antes de calcular:</p>
<ul>
<li>Caso 3 (<span class="math inline">\(E\)</span> doble respecto al caso 2): <span class="math inline">\(\Delta T_3 = 4 \times \Delta T_2\)</span></li>
<li>Caso 4 (<span class="math inline">\(\sigma\)</span> doble respecto al caso 2): <span class="math inline">\(\Delta T_4 = 2 \times \Delta T_2\)</span></li>
</ul>
<p>Para el caso 6: combina <span class="math inline">\(\sigma\)</span> doble, <span class="math inline">\(E\)</span> doble y <span class="math inline">\(\tau\)</span> diez veces mayor que en el caso 2. Predice el factor de aumento antes de calcular.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>✓ Respuesta — Actividad 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Conversiones previas:</strong></p>
<p><span class="math display">\[
1~\mathrm{kV/cm} = 10^5~\mathrm{V/m}
\qquad
100~\mu\mathrm{s} = 10^{-4}~\mathrm{s}
\qquad
1~\mathrm{ms} = 10^{-3}~\mathrm{s}
\]</span></p>
<p><span class="math display">\[
\Delta T = \frac{\sigma\, E^2\, \tau}{\rho\, c_p} = \frac{\sigma\, E^2\, \tau}{1000 \times 4180}
\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th><span class="math inline">\(\sigma\)</span></th>
<th><span class="math inline">\(E~\mathrm{[V/m]}\)</span></th>
<th><span class="math inline">\(\tau~\mathrm{[s]}\)</span></th>
<th><span class="math inline">\(\Delta T~\mathrm{[K]}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1.0</td>
<td><span class="math inline">\(5\times10^4\)</span></td>
<td><span class="math inline">\(10^{-4}\)</span></td>
<td><span class="math inline">\(0.060\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td>1.0</td>
<td><span class="math inline">\(10^5\)</span></td>
<td><span class="math inline">\(10^{-4}\)</span></td>
<td><span class="math inline">\(0.239\)</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td>1.0</td>
<td><span class="math inline">\(2\times10^5\)</span></td>
<td><span class="math inline">\(10^{-4}\)</span></td>
<td><span class="math inline">\(0.957\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td>2.0</td>
<td><span class="math inline">\(10^5\)</span></td>
<td><span class="math inline">\(10^{-4}\)</span></td>
<td><span class="math inline">\(0.479\)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td>1.0</td>
<td><span class="math inline">\(10^5\)</span></td>
<td><span class="math inline">\(10^{-3}\)</span></td>
<td><span class="math inline">\(2.392\)</span></td>
</tr>
<tr class="even">
<td>6</td>
<td>2.0</td>
<td><span class="math inline">\(2\times10^5\)</span></td>
<td><span class="math inline">\(10^{-3}\)</span></td>
<td><span class="math inline">\(19.14\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Interpretación:</strong></p>
<ol type="1">
<li><p>El caso 6 produce el mayor calentamiento (<span class="math inline">\(19.1~\mathrm{K}\)</span>), porque combina alta conductividad, campo intenso y pulso largo.</p></li>
<li><p>Duplicar <span class="math inline">\(E\)</span> cuadruplica <span class="math inline">\(\Delta T\)</span> (casos 2 → 3: <span class="math inline">\(0.239 \times 4 = 0.957~\mathrm{K}\)</span>). Duplicar <span class="math inline">\(\sigma\)</span> o <span class="math inline">\(\tau\)</span> solo lo duplica. El campo tiene el mayor efecto relativo.</p></li>
<li><p>El campo aparece como <span class="math inline">\(E^2\)</span> porque la potencia disipada <span class="math inline">\(q = \sigma E^2\)</span> ya es cuadrática en <span class="math inline">\(E\)</span>: la corriente <span class="math inline">\(J = \sigma E\)</span> y la potencia por unidad de volumen <span class="math inline">\(q = J \cdot E = \sigma E^2\)</span>.</p></li>
<li><p>Un aumento de <span class="math inline">\(\sim 1~\mathrm{K}\)</span> (caso 3) comienza a ser biológicamente relevante si se acumula con múltiples pulsos. El caso 6, con <span class="math inline">\(\sim 19~\mathrm{K}\)</span>, sería claramente problemático: podría desnaturalizar proteínas, alterar membranas y comprometer la viabilidad celular.</p></li>
<li><p>Esta estimación no incluye difusión térmica durante el pulso, heterogeneidad del tejido, ni acumulación entre pulsos. En geometrías reales el campo no es uniforme y existen puntos calientes cerca de los electrodos.</p></li>
<li><p>Con <span class="math inline">\(N\)</span> pulsos repetidos y sin tiempo suficiente para disipar el calor: <span class="math inline">\(\Delta T_{\mathrm{total}} \approx N \times \Delta T_{\mathrm{pulso}}\)</span>. Para frecuencias altas o trenes densos, el calentamiento puede sumarse significativamente.</p></li>
</ol>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="actividad-integradora" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Actividad integradora</h1>
<p><em>Nivel: avanzado</em></p>
<section id="objetivo-4" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="objetivo-4"><span class="header-section-number">7.1</span> Objetivo</h2>
<p>Conectar los cuatro módulos del portal en una interpretación biofísica unificada.</p>
</section>
<section id="situación-problema" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="situación-problema"><span class="header-section-number">7.2</span> Situación problema</h2>
<p>Se desea aplicar un protocolo de electroporación a células aproximadamente esféricas de radio <span class="math inline">\(a = 10~\mu\mathrm{m}\)</span>, en un medio con conductividad <span class="math inline">\(\sigma = 1.2~\mathrm{S/m}\)</span>, usando un pulso rectangular de duración <span class="math inline">\(\tau = 100~\mu\mathrm{s}\)</span>.</p>
<p>Se evalúan tres protocolos:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Protocolo</th>
<th><span class="math inline">\(E_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td><span class="math inline">\(0.5~\mathrm{kV/cm}\)</span></td>
</tr>
<tr class="even">
<td>B</td>
<td><span class="math inline">\(1.0~\mathrm{kV/cm}\)</span></td>
</tr>
<tr class="odd">
<td>C</td>
<td><span class="math inline">\(2.0~\mathrm{kV/cm}\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="preguntas-orientadoras-4" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="preguntas-orientadoras-4"><span class="header-section-number">7.3</span> Preguntas orientadoras</h2>
<ol type="1">
<li>Estime <span class="math inline">\(\Delta V_m^{\mathrm{ind}}\)</span> en los polos para cada protocolo.</li>
<li>¿Cuál protocolo podría superar el umbral aproximado de <span class="math inline">\(1~\mathrm{V}\)</span>?</li>
<li>¿Cómo cambiaría cualitativamente la barrera energética <span class="math inline">\(\Delta G_c\)</span> al pasar del protocolo A al C?</li>
<li>Estime <span class="math inline">\(\Delta T\)</span> para cada protocolo.</li>
<li>¿Cuál protocolo parece más favorable para inducir permeabilización con calentamiento moderado?</li>
<li>¿Por qué la decisión experimental no debe basarse solo en una ecuación?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Pista — Actividad integradora
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Esta actividad une los resultados de las cuatro anteriores. Aplica cada modelo por separado y luego compara:</p>
<p><strong>Voltaje inducido:</strong> usa <span class="math inline">\(\Delta V_m^{\mathrm{ind}} = 1.5 \times a \times E_0\)</span> con <span class="math inline">\(a = 10^{-5}~\mathrm{m}\)</span>.</p>
<p><strong>Barrera energética:</strong> no es necesario calcularlo numéricamente. Razona cualitativamente: al aumentar <span class="math inline">\(V_m^{\mathrm{tot}}\)</span>, el denominador <span class="math inline">\(A = \pi\Gamma + kV^2\)</span> crece, y <span class="math inline">\(\Delta G_c = \pi^2\gamma^2/A\)</span> disminuye.</p>
<p><strong>Calentamiento:</strong> usa <span class="math inline">\(\Delta T = \sigma E^2 \tau / (\rho c_p)\)</span> con <span class="math inline">\(\sigma = 1.2~\mathrm{S/m}\)</span>, <span class="math inline">\(\tau = 10^{-4}~\mathrm{s}\)</span>, <span class="math inline">\(\rho c_p = 4.18\times10^6~\mathrm{J\,m^{-3}\,K^{-1}}\)</span>.</p>
<p>El protocolo B suele ser el punto de equilibrio típico: campo suficiente para inducir permeabilización, calentamiento aún moderado. Verifica los números antes de concluir.</p>
<p>Para la pregunta 6, reflexiona sobre qué aspecto <strong>no</strong> cubre cada modelo por separado.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>✓ Respuesta — Actividad integradora
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Voltaje transmembrana inducido en los polos</strong> (<span class="math inline">\(a = 10^{-5}~\mathrm{m}\)</span>, <span class="math inline">\(f = 1.5\)</span>):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Protocolo</th>
<th><span class="math inline">\(E_0~\mathrm{[V/m]}\)</span></th>
<th><span class="math inline">\(\Delta V_m^{\mathrm{ind}}~\mathrm{[V]}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td><span class="math inline">\(5\times10^4\)</span></td>
<td><span class="math inline">\(0.75\)</span></td>
</tr>
<tr class="even">
<td>B</td>
<td><span class="math inline">\(10^5\)</span></td>
<td><span class="math inline">\(1.50\)</span></td>
</tr>
<tr class="odd">
<td>C</td>
<td><span class="math inline">\(2\times10^5\)</span></td>
<td><span class="math inline">\(3.00\)</span></td>
</tr>
</tbody>
</table>
<p><strong>2.</strong> Solo los protocolos B y C superan el umbral de <span class="math inline">\(1~\mathrm{V}\)</span>. El protocolo A (<span class="math inline">\(0.75~\mathrm{V}\)</span>) queda por debajo, lo que sugiere permeabilización subumbral o muy débil.</p>
<p><strong>3. Barrera energética</strong> (razonamiento cualitativo): al pasar de A a C, <span class="math inline">\(V_m^{\mathrm{tot}}\)</span> crece cuatro veces, el término <span class="math inline">\(kV^2\)</span> en el denominador aumenta notablemente y <span class="math inline">\(\Delta G_c\)</span> disminuye de forma significativa. Con <span class="math inline">\(V \approx 0.75~\mathrm{V}\)</span> (protocolo A) la barrera es alta; con <span class="math inline">\(V \approx 1.5~\mathrm{V}\)</span> (protocolo B) cae a valores comparables a las fluctuaciones térmicas; con <span class="math inline">\(V \approx 3.0~\mathrm{V}\)</span> (protocolo C) la nucleación sería prácticamente espontánea.</p>
<p><strong>4. Calentamiento Joule</strong> (<span class="math inline">\(\sigma = 1.2~\mathrm{S/m}\)</span>, <span class="math inline">\(\tau = 10^{-4}~\mathrm{s}\)</span>):</p>
<p><span class="math display">\[
\Delta T = \frac{1.2 \times E^2 \times 10^{-4}}{4.18\times10^6}
\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Protocolo</th>
<th><span class="math inline">\(E~\mathrm{[V/m]}\)</span></th>
<th><span class="math inline">\(\Delta T~\mathrm{[K]}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td><span class="math inline">\(5\times10^4\)</span></td>
<td><span class="math inline">\(0.072\)</span></td>
</tr>
<tr class="even">
<td>B</td>
<td><span class="math inline">\(10^5\)</span></td>
<td><span class="math inline">\(0.287\)</span></td>
</tr>
<tr class="odd">
<td>C</td>
<td><span class="math inline">\(2\times10^5\)</span></td>
<td><span class="math inline">\(1.148\)</span></td>
</tr>
</tbody>
</table>
<p><strong>5.</strong> El protocolo B es el más equilibrado: supera el umbral de voltaje inducido (<span class="math inline">\(1.5~\mathrm{V}\)</span>), reduce la barrera energética a valores donde la nucleación es probable, y produce un calentamiento de solo <span class="math inline">\(\sim 0.29~\mathrm{K}\)</span> por pulso. El protocolo C favorece más la permeabilización, pero el calentamiento de <span class="math inline">\(\sim 1.1~\mathrm{K}\)</span> por pulso puede acumularse con múltiples pulsos.</p>
<p><strong>6.</strong> Ninguna ecuación es suficiente sola:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Modelo</th>
<th>Lo que no incluye</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Schwan (<span class="math inline">\(\Delta V_m^{\mathrm{ind}}\)</span>)</td>
<td>Dinámica temporal, heterogeneidad celular, geometría no esférica</td>
</tr>
<tr class="even">
<td>RC (carga temporal)</td>
<td>Distribución espacial del voltaje, efectos no lineales</td>
</tr>
<tr class="odd">
<td>Energía del poro (<span class="math inline">\(\Delta G_c\)</span>)</td>
<td>Barrera hidrofóbica, fluctuaciones estocásticas, cierre del poro</td>
</tr>
<tr class="even">
<td>Calentamiento Joule (<span class="math inline">\(\Delta T\)</span>)</td>
<td>Difusión térmica, acumulación de pulsos, geometría del electrodo</td>
</tr>
</tbody>
</table>
<p>El diseño racional de un protocolo requiere integrar todos estos aspectos: el campo debe ser suficiente para inducir voltaje y reducir la barrera, el pulso debe ser suficientemente largo para cargar la membrana, y el calentamiento acumulado debe mantenerse dentro de límites biológicamente tolerables.</p>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="cierre" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Cierre</h1>
<p>Estas actividades muestran que la electroporación no depende de un único parámetro. La respuesta celular surge de la interacción entre la geometría celular, la intensidad del campo eléctrico, la duración del pulso, la dinámica capacitiva de la membrana, la barrera energética para formar poros y la disipación Joule en el medio.</p>
<p>Por ello, el diseño racional de protocolos de electroporación requiere combinar modelos eléctricos, térmicos y biofísicos.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Actividades de aprendizaje"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu"># Propósito de las actividades</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Las siguientes actividades están diseñadas para reforzar los conceptos biofísicos centrales de la electroporación mediante análisis cuantitativo, interpretación gráfica y razonamiento físico.</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>El objetivo no es memorizar ecuaciones, sino comprender cómo el campo eléctrico externo, el tamaño celular, la dinámica capacitiva de la membrana, la energía libre de formación de poros y la disipación Joule se relacionan entre sí.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu"># Cómo enfrentar estas actividades</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>Antes de abrir cualquier pista o respuesta, se recomienda seguir este orden de trabajo:</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>**Paso 1 — Lee el enunciado completo** sin abrir nada. Identifica qué se pregunta, qué datos tienes y qué ecuación podría ser relevante.</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>**Paso 2 — Intenta resolverlo por tu cuenta** durante al menos 10 minutos. Escribe en papel las unidades de cada variable. Los errores más frecuentes en estas actividades son de conversión de unidades, no de conceptos.</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>**Paso 3 — Si estás bloqueado, abre la pista.** La pista no da la respuesta: da una orientación sobre cómo empezar o qué verificar. Úsala como un empuje, no como un atajo.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>**Paso 4 — Después de obtener tu resultado, abre la respuesta** para comparar. Si tu número coincide, verifica también la interpretación física. Si no coincide, busca el paso donde difieren antes de leer la solución completa.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>**Paso 5 — Escribe con tus propias palabras** qué aprendiste de esa actividad. Una frase es suficiente.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">## Sobre las respuestas</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>Las respuestas incluyen el desarrollo completo y la interpretación física. No están ahí para copiarse, sino para que puedas identificar exactamente dónde razonaste diferente. El valor está en ese proceso de comparación, no en el número final.</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="fu"># Actividad 1: voltaje transmembrana inducido</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>*Nivel: básico*</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivo</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>Estimar el voltaje transmembrana inducido por un campo eléctrico externo y analizar en qué condiciones se puede alcanzar un umbral aproximado de electroporación.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="fu">## Contexto físico</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>Para una célula aproximadamente esférica, el voltaje transmembrana inducido puede estimarse mediante la ecuación de Schwan:</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>\Delta V_m^{\mathrm{ind}}(\theta)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>1.5\,a\,E_0\cos\theta</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>donde $a$ es el radio celular, $E_0$ el campo eléctrico externo y $\theta$ el ángulo medido respecto a la dirección del campo. En los polos ($\theta = 0$, $\cos\theta = 1$):</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>\Delta V_m^{\mathrm{ind}}</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>1.5\,a\,E_0</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="fu">## Procedimiento</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>Considere una célula de radio $a = 10~\mu\mathrm{m}$. Calcule $\Delta V_m^{\mathrm{ind}}$ en los polos para los siguientes campos eléctricos y complete la tabla:</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Caso <span class="pp">|</span> $E_0$ <span class="pp">|</span> $\Delta V_m^{\mathrm{ind}}$ <span class="pp">|</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> $0.2~\mathrm{kV/cm}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> $0.5~\mathrm{kV/cm}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> $1.0~\mathrm{kV/cm}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> $1.5~\mathrm{kV/cm}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> $2.0~\mathrm{kV/cm}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="fu">## Preguntas orientadoras</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>¿Para qué valores de $E_0$ se supera aproximadamente $\Delta V_m^{\mathrm{ind}} = 1~\mathrm{V}$?</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>¿Por qué una célula más grande alcanza un mayor voltaje inducido bajo el mismo campo?</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>¿Qué ocurriría si el radio celular fuera $5~\mu\mathrm{m}$ en lugar de $10~\mu\mathrm{m}$?</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>¿Por qué el voltaje inducido es máximo en los polos y nulo cerca del ecuador?</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>¿Qué limitaciones tiene usar esta ecuación como criterio directo de electroporación?</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="fu">## 💡 Pista — Actividad 1</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>La clave está en las unidades. La ecuación usa metros y V/m, pero los datos están en $\mu$m y kV/cm. Antes de sustituir, convierte todo al SI:</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>1~\mu\mathrm{m} = 10^{-6}~\mathrm{m}</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>1~\mathrm{kV/cm} = \frac{10^3~\mathrm{V}}{10^{-2}~\mathrm{m}} = 10^5~\mathrm{V/m}</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>Después la ecuación es directa: multiplica $1.5 \times a \times E_0$. El resultado debe quedar en voltios.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>Para las preguntas conceptuales: la ecuación de Schwan es lineal tanto en $a$ como en $E_0$. Eso significa que si duplicas el radio, el voltaje se duplica; si duplicas el campo, también se duplica. Y $\cos\theta$ vale 1 en los polos y 0 en el ecuador.</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="fu">## ✓ Respuesta — Actividad 1</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>**Conversión de unidades:**</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>a = 10~\mu\mathrm{m} = 10 \times 10^{-6}~\mathrm{m} = 10^{-5}~\mathrm{m}</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>1~\mathrm{kV/cm} = 10^5~\mathrm{V/m}</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>**Tabla de resultados:**</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Caso <span class="pp">|</span> $E_0$ <span class="pp">|</span> $E_0$ <span class="co">[</span><span class="ot">V/m</span><span class="co">]</span> <span class="pp">|</span> $\Delta V_m^{\mathrm{ind}} = 1.5 \times 10^{-5} \times E_0$ <span class="pp">|</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> $0.2~\mathrm{kV/cm}$ <span class="pp">|</span> $2.0\times10^4$ <span class="pp">|</span> $0.300~\mathrm{V}$ <span class="pp">|</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> $0.5~\mathrm{kV/cm}$ <span class="pp">|</span> $5.0\times10^4$ <span class="pp">|</span> $0.750~\mathrm{V}$ <span class="pp">|</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> $1.0~\mathrm{kV/cm}$ <span class="pp">|</span> $1.0\times10^5$ <span class="pp">|</span> $1.500~\mathrm{V}$ <span class="pp">|</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> $1.5~\mathrm{kV/cm}$ <span class="pp">|</span> $1.5\times10^5$ <span class="pp">|</span> $2.250~\mathrm{V}$ <span class="pp">|</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> $2.0~\mathrm{kV/cm}$ <span class="pp">|</span> $2.0\times10^5$ <span class="pp">|</span> $3.000~\mathrm{V}$ <span class="pp">|</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>**Interpretación:**</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>El umbral de $1~\mathrm{V}$ se supera a partir de $E_0 = 1.0~\mathrm{kV/cm}$ (casos 3, 4 y 5).</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>La ecuación es lineal en $a$: $\Delta V_m^{\mathrm{ind}} \propto a$. Una célula más grande presenta más separación entre sus polos bajo el mismo campo externo y acumula más diferencia de potencial.</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Si $a = 5~\mu\mathrm{m}$, todos los voltajes se reducirían a la mitad. Para superar $1~\mathrm{V}$ habría que aplicar $E_0 = 2.0~\mathrm{kV/cm}$.</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>El factor $\cos\theta$ es máximo en $\theta = 0$ (polo alineado con el campo) y se anula en $\theta = \pi/2$ (ecuador). Esto refleja la geometría de la polarización dipolar inducida por el campo externo.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Limitaciones principales: la ecuación asume estado cuasiestático, célula perfectamente esférica, membrana sin conductancia, campo uniforme y ausencia de interacciones entre células. La electroporación también depende de la duración del pulso y de la barrera energética del poro.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="fu"># Actividad 2: carga temporal de la membrana</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>*Nivel: básico*</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivo</span></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>Analizar cómo la duración del pulso afecta la carga capacitiva de la membrana y el valor máximo alcanzado por el voltaje transmembrana inducido.</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="fu">## Contexto físico</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>Durante un pulso rectangular que comienza en $t_0$, la componente inducida del voltaje transmembrana evoluciona como:</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>\Delta V_m^{\mathrm{ind}}(t)</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>\Delta V_{m,\max}^{\mathrm{ind}}</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>\left(1-e^{-(t-t_0)/\tau_m}\right)</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>t_0 \leq t \leq t_0 + t_p</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>Al final del pulso:</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>\Delta V_m^{\mathrm{ind}}(t_0 + t_p)</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>\Delta V_{m,\max}^{\mathrm{ind}}</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>\left(1-e^{-t_p/\tau_m}\right)</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="fu">## Procedimiento</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>Suponga $\Delta V_{m,\max}^{\mathrm{ind}} = 1.5~\mathrm{V}$ y $\tau_m = 1~\mu\mathrm{s}$. Calcule el voltaje alcanzado al final del pulso y la fracción respecto al máximo para cada caso:</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Caso <span class="pp">|</span> $t_p$ <span class="pp">|</span> $\Delta V_m^{\mathrm{ind}}(t_0 + t_p)$ <span class="pp">|</span> Fracción del máximo <span class="pp">|</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> $100~\mathrm{ns}$ <span class="pp">|</span> ? <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> $10~\mu\mathrm{s}$ <span class="pp">|</span> ? <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> $1~\mathrm{ms}$ <span class="pp">|</span> ? <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="fu">## Preguntas orientadoras</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>¿Qué fracción de $\Delta V_{m,\max}^{\mathrm{ind}}$ se alcanza en cada caso?</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>¿Cuál de los tres pulsos permite que la membrana se cargue casi completamente?</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>¿Por qué un pulso de $100~\mathrm{ns}$ puede no permitir que la membrana alcance el valor esperado por la ecuación de Schwan?</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>¿Por qué los pulsos más cortos pueden requerir campos eléctricos mayores?</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>¿Qué diferencia conceptual hay entre aplicar un campo intenso durante nanosegundos y uno menor durante microsegundos?</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="fu">## 💡 Pista — Actividad 2</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>La clave es comparar $t_p$ con $\tau_m = 1~\mu\mathrm{s}$. La fracción de carga alcanzada depende del cociente $t_p / \tau_m$:</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si $t_p \ll \tau_m$: el exponencial apenas decae, la membrana se carga muy poco.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si $t_p \approx \tau_m$: la membrana alcanza $1 - e^{-1} \approx 63\%$ del máximo.</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si $t_p \gg \tau_m$: el exponencial se acerca a cero, la membrana alcanza casi el $100\%$.</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>Convierte las duraciones al SI antes de calcular:</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>100~\mathrm{ns} = 10^{-7}~\mathrm{s}</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>10~\mu\mathrm{s} = 10^{-5}~\mathrm{s}</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>1~\mathrm{ms} = 10^{-3}~\mathrm{s}</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>\tau_m = 10^{-6}~\mathrm{s}</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>Calcula primero el cociente $t_p/\tau_m$, luego evalúa $1 - e^{-t_p/\tau_m}$.</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="fu">## ✓ Respuesta — Actividad 2</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>**Expresión a evaluar:**</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>\Delta V_m^{\mathrm{ind}}(t_0 + t_p)</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>1.5 \times \left(1 - e^{-t_p/\tau_m}\right)~\mathrm{V}</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Caso <span class="pp">|</span> $t_p$ <span class="pp">|</span> $t_p/\tau_m$ <span class="pp">|</span> $1 - e^{-t_p/\tau_m}$ <span class="pp">|</span> Voltaje alcanzado <span class="pp">|</span> Fracción <span class="pp">|</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|---|---|</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> $100~\mathrm{ns}$ <span class="pp">|</span> $0.1$ <span class="pp">|</span> $0.0952$ <span class="pp">|</span> $0.143~\mathrm{V}$ <span class="pp">|</span> $9.5\%$ <span class="pp">|</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> $10~\mu\mathrm{s}$ <span class="pp">|</span> $10$ <span class="pp">|</span> $\approx 1.000$ <span class="pp">|</span> $\approx 1.500~\mathrm{V}$ <span class="pp">|</span> $\approx 100\%$ <span class="pp">|</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> $1~\mathrm{ms}$ <span class="pp">|</span> $1000$ <span class="pp">|</span> $\approx 1.000$ <span class="pp">|</span> $\approx 1.500~\mathrm{V}$ <span class="pp">|</span> $\approx 100\%$ <span class="pp">|</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>**Interpretación:**</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>El pulso de $100~\mathrm{ns}$ solo carga la membrana hasta el $9.5\%$ del valor máximo. Los pulsos de $10~\mu\mathrm{s}$ y $1~\mathrm{ms}$ la cargan prácticamente al $100\%$, ya que $t_p \gg \tau_m$.</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Los casos 2 y 3 permiten alcanzar la carga completa.</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>La ecuación de Schwan describe el voltaje en estado cuasiestático (para $t_p \gg \tau_m$). Un pulso de $100~\mathrm{ns}$ es mucho más corto que $\tau_m$, por lo que la membrana no tiene tiempo de cargarse hasta ese valor.</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Si el pulso es corto, la membrana solo alcanza una fracción pequeña del voltaje máximo. Para compensar y llegar al mismo voltaje absoluto habría que aumentar $\Delta V_{m,\max}^{\mathrm{ind}} = 1.5\,a\,E_0$, es decir, aumentar el campo $E_0$.</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Un campo intenso durante nanosegundos puede penetrar al interior celular sin cargar la membrana significativamente (pulsos nanosegundo o nsPEF). Un campo menor durante microsegundos o milisegundos carga completamente la membrana y produce permeabilización clásica de la bicapa lipídica.</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a><span class="fu"># Actividad 3: energía libre de formación del poro</span></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>*Nivel: medio*</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivo</span></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>Interpretar cómo el voltaje transmembrana total modifica el paisaje de energía libre asociado a la formación de un poro de membrana.</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="fu">## Contexto físico</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>El modelo simplificado para la energía libre de un poro de radio $r$ es:</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>\Delta G(r,V_m^{\mathrm{tot}})</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>\approx</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>2\pi r\gamma</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>-</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>\pi r^2\Gamma</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>-</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>k r^2\left(V_m^{\mathrm{tot}}\right)^2</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>El radio crítico y la barrera energética se obtienen del máximo de $\Delta G(r)$:</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>r_c</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>\frac{\pi\gamma}{\pi\Gamma+k\left(V_m^{\mathrm{tot}}\right)^2}</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>\Delta G_c</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>=</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>\frac{\pi^2\gamma^2}{\pi\Gamma+k\left(V_m^{\mathrm{tot}}\right)^2}</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="fu">## Procedimiento</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>Use los parámetros físicos justificados en el módulo correspondiente:</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>\gamma = 9.2~\mathrm{pN}</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>\Gamma = 1~\mathrm{mN/m}</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a>k = 556~\mathrm{mF/m^2}</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>T = 298~\mathrm{K}</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>Calcule $r_c$ y $\Delta G_c$ (en unidades de $k_BT$) para cada voltaje:</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Caso <span class="pp">|</span> $V_m^{\mathrm{tot}}$ <span class="pp">|</span> $r_c$ <span class="pp">|</span> $\Delta G_c$ <span class="pp">|</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> $0~\mathrm{mV}$ <span class="pp">|</span> ? <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> $150~\mathrm{mV}$ <span class="pp">|</span> ? <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> $300~\mathrm{mV}$ <span class="pp">|</span> ? <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> $450~\mathrm{mV}$ <span class="pp">|</span> ? <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> $600~\mathrm{mV}$ <span class="pp">|</span> ? <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a><span class="fu">## Preguntas orientadoras</span></span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>¿Cómo cambian $r_c$ y $\Delta G_c$ al aumentar $V_m^{\mathrm{tot}}$?</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>¿Por qué el voltaje aparece elevado al cuadrado en el término eléctrico?</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>¿Qué significa físicamente que la barrera $\Delta G_c$ disminuya?</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>¿Por qué una barrera menor no implica ruptura irreversible inmediata?</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>¿A partir de qué voltaje la barrera cae por debajo de $\sim 5\,k_BT$?</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>¿Qué diferencias conceptuales hay entre nucleación, expansión y daño irreversible?</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="fu">## 💡 Pista — Actividad 3</span></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>Primero convierte todo al SI:</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a>\gamma = 9.2 \times 10^{-12}~\mathrm{J/m}</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a>\Gamma = 10^{-3}~\mathrm{J/m^2}</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a>k = 0.556~\mathrm{F/m^2}</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>k_BT = 1.381 \times 10^{-23} \times 298 \approx 4.114 \times 10^{-21}~\mathrm{J}</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a>Los voltajes también en V: $150~\mathrm{mV} = 0.150~\mathrm{V}$, etc.</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a>Calcula primero el denominador $A = \pi\Gamma + k V^2$ para cada voltaje. Luego:</span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>r_c = \frac{\pi\gamma}{A}~\mathrm{<span class="co">[</span><span class="ot">m</span><span class="co">]</span>}</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>\quad\rightarrow\quad</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>r_c~\mathrm{<span class="co">[</span><span class="ot">nm</span><span class="co">]</span>} = r_c~\mathrm{<span class="co">[</span><span class="ot">m</span><span class="co">]</span>} \times 10^9</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a>\Delta G_c = \frac{\pi^2\gamma^2}{A}~\mathrm{<span class="co">[</span><span class="ot">J</span><span class="co">]</span>}</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>\quad\rightarrow\quad</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a>\Delta G_c~<span class="co">[</span><span class="ot">k_BT</span><span class="co">]</span> = \frac{\Delta G_c~\mathrm{<span class="co">[</span><span class="ot">J</span><span class="co">]</span>}}{k_BT}</span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>Observa cómo $A$ crece con $V^2$: a mayor voltaje, mayor denominador, y por tanto menor $r_c$ y menor $\Delta G_c$.</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a><span class="fu">## ✓ Respuesta — Actividad 3</span></span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a>**Parámetros en SI:**</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a>\gamma = 9.2 \times 10^{-12}~\mathrm{J/m}</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a>\Gamma = 10^{-3}~\mathrm{J/m^2}</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a>k = 0.556~\mathrm{F/m^2}</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a>k_BT = 4.114 \times 10^{-21}~\mathrm{J}</span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>**Denominador:** $A = \pi\Gamma + k V^2$</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Caso <span class="pp">|</span> $V_m^{\mathrm{tot}}$ <span class="pp">|</span> $A~\mathrm{<span class="co">[</span><span class="ot">J/m^2</span><span class="co">]</span>}$ <span class="pp">|</span> $r_c~\mathrm{<span class="co">[</span><span class="ot">nm</span><span class="co">]</span>}$ <span class="pp">|</span> $\Delta G_c~<span class="co">[</span><span class="ot">k_BT</span><span class="co">]</span>$ <span class="pp">|</span></span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|---|</span></span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> $0~\mathrm{mV}$ <span class="pp">|</span> $3.14 \times 10^{-3}$ <span class="pp">|</span> $9.20$ <span class="pp">|</span> $64.6$ <span class="pp">|</span></span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> $150~\mathrm{mV}$ <span class="pp">|</span> $1.566 \times 10^{-2}$ <span class="pp">|</span> $1.847$ <span class="pp">|</span> $13.0$ <span class="pp">|</span></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> $300~\mathrm{mV}$ <span class="pp">|</span> $5.135 \times 10^{-2}$ <span class="pp">|</span> $0.544$ <span class="pp">|</span> $3.82$ <span class="pp">|</span></span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> $450~\mathrm{mV}$ <span class="pp">|</span> $1.128 \times 10^{-1}$ <span class="pp">|</span> $0.250$ <span class="pp">|</span> $1.75$ <span class="pp">|</span></span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> $600~\mathrm{mV}$ <span class="pp">|</span> $2.003 \times 10^{-1}$ <span class="pp">|</span> $0.142$ <span class="pp">|</span> $1.00$ <span class="pp">|</span></span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a>**Interpretación:**</span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Al aumentar $V_m^{\mathrm{tot}}$, tanto $r_c$ como $\Delta G_c$ disminuyen progresivamente, porque el término $kV^2$ crece y aumenta el denominador $A$.</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>El término eléctrico es $-kr^2V^2$. La energía almacenada en un campo eléctrico es proporcional a $V^2$ (como en un condensador). El efecto no depende del signo del voltaje, solo de su magnitud al cuadrado.</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Una barrera $\Delta G_c$ menor significa que las fluctuaciones térmicas tienen mayor probabilidad de superarla y nuclearse. Cuanto más baja la barrera, más probable la formación espontánea de poros.</span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>La superación de la barrera de nucleación abre el poro hidrofílico, pero la expansión posterior depende de si el campo y la tensión superficial favorecen el crecimiento. Un poro puede nuclearse y luego cerrarse si la energía para expandirse sigue siendo desfavorable.</span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Entre $V = 300~\mathrm{mV}$ y $V = 150~\mathrm{mV}$: a $300~\mathrm{mV}$ la barrera ya es $3.82\,k_BT$, claramente por debajo de $5\,k_BT$. A $150~\mathrm{mV}$ es $13.0\,k_BT$, aún alta. Por tanto, el umbral de $5\,k_BT$ se cruza entre $150~\mathrm{mV}$ y $300~\mathrm{mV}$.</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Nucleación**: formación del primer poro hidrofílico estable (superar $\Delta G_c$). **Expansión**: crecimiento del radio una vez nucleado. **Daño irreversible**: expansión tan grande que la membrana no recupera su integridad (requiere superar la barrera de ruptura, que es mucho mayor a voltajes bajos, $\sim 300\,k_BT$).</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a><span class="fu"># Actividad 4: calentamiento Joule</span></span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a>*Nivel: medio*</span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivo</span></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>Estimar el aumento de temperatura producido por disipación Joule durante un pulso eléctrico y discutir cuándo el calentamiento puede dejar de ser despreciable.</span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a><span class="fu">## Contexto físico</span></span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a>La potencia volumétrica disipada en un medio conductor es:</span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>q = \sigma E^2</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a>Para un pulso corto, bajo aproximación adiabática:</span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a>\Delta T</span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a>\approx</span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a>\frac{\sigma E^2\tau}{\rho c_p}</span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a>donde $\sigma$ es la conductividad, $E$ el campo eléctrico, $\tau$ la duración del pulso, $\rho$ la densidad y $c_p$ el calor específico.</span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a><span class="fu">## Procedimiento</span></span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a>Use $\rho = 1000~\mathrm{kg\,m^{-3}}$ y $c_p = 4180~\mathrm{J\,kg^{-1}\,K^{-1}}$. Recuerde que $1~\mathrm{kV/cm} = 10^5~\mathrm{V/m}$.</span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Caso <span class="pp">|</span> $\sigma~\mathrm{<span class="co">[</span><span class="ot">S/m</span><span class="co">]</span>}$ <span class="pp">|</span> $E~\mathrm{<span class="co">[</span><span class="ot">kV/cm</span><span class="co">]</span>}$ <span class="pp">|</span> $\tau$ <span class="pp">|</span> $\Delta T~\mathrm{<span class="co">[</span><span class="ot">K</span><span class="co">]</span>}$ <span class="pp">|</span></span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---|</span></span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 1.0 <span class="pp">|</span> 0.5 <span class="pp">|</span> $100~\mu\mathrm{s}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 1.0 <span class="pp">|</span> 1.0 <span class="pp">|</span> $100~\mu\mathrm{s}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> 1.0 <span class="pp">|</span> 2.0 <span class="pp">|</span> $100~\mu\mathrm{s}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> 2.0 <span class="pp">|</span> 1.0 <span class="pp">|</span> $100~\mu\mathrm{s}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> 1.0 <span class="pp">|</span> 1.0 <span class="pp">|</span> $1~\mathrm{ms}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 6 <span class="pp">|</span> 2.0 <span class="pp">|</span> 2.0 <span class="pp">|</span> $1~\mathrm{ms}$ <span class="pp">|</span> ? <span class="pp">|</span></span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a><span class="fu">## Preguntas orientadoras</span></span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>¿Cuál de los casos produce el mayor calentamiento?</span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>¿Qué variable tiene mayor efecto sobre $\Delta T$: duplicar $E$, $\sigma$ o $\tau$?</span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>¿Por qué el campo eléctrico tiene un efecto cuadrático sobre el calentamiento?</span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>¿En qué casos el calentamiento podría ser biológicamente relevante?</span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>¿Por qué esta estimación no reemplaza un modelo completo de transferencia de calor?</span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>¿Cómo cambiaría $\Delta T$ con un tren de muchos pulsos?</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a><span class="fu">## 💡 Pista — Actividad 4</span></span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a>La ecuación $\Delta T = \sigma E^2 \tau / (\rho c_p)$ tiene tres variables independientes. Antes de calcular, piensa cualitativamente qué ocurre al duplicar cada una:</span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Duplicar $\sigma$: $\Delta T$ se **duplica** (efecto lineal).</span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Duplicar $\tau$: $\Delta T$ se **duplica** (efecto lineal).</span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Duplicar $E$: $\Delta T$ se **cuadruplica** (efecto cuadrático, ya que $E$ aparece como $E^2$).</span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a>Usa esto para predecir los casos 3 y 4 a partir del caso 2 antes de calcular:</span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Caso 3 ($E$ doble respecto al caso 2): $\Delta T_3 = 4 \times \Delta T_2$</span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Caso 4 ($\sigma$ doble respecto al caso 2): $\Delta T_4 = 2 \times \Delta T_2$</span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a>Para el caso 6: combina $\sigma$ doble, $E$ doble y $\tau$ diez veces mayor que en el caso 2. Predice el factor de aumento antes de calcular.</span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a><span class="fu">## ✓ Respuesta — Actividad 4</span></span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a>**Conversiones previas:**</span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a>1~\mathrm{kV/cm} = 10^5~\mathrm{V/m}</span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a>100~\mu\mathrm{s} = 10^{-4}~\mathrm{s}</span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-455"><a href="#cb1-455" aria-hidden="true" tabindex="-1"></a>1~\mathrm{ms} = 10^{-3}~\mathrm{s}</span>
<span id="cb1-456"><a href="#cb1-456" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-457"><a href="#cb1-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-458"><a href="#cb1-458" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-459"><a href="#cb1-459" aria-hidden="true" tabindex="-1"></a>\Delta T = \frac{\sigma\, E^2\, \tau}{\rho\, c_p} = \frac{\sigma\, E^2\, \tau}{1000 \times 4180}</span>
<span id="cb1-460"><a href="#cb1-460" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-461"><a href="#cb1-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-462"><a href="#cb1-462" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Caso <span class="pp">|</span> $\sigma$ <span class="pp">|</span> $E~\mathrm{<span class="co">[</span><span class="ot">V/m</span><span class="co">]</span>}$ <span class="pp">|</span> $\tau~\mathrm{<span class="co">[</span><span class="ot">s</span><span class="co">]</span>}$ <span class="pp">|</span> $\Delta T~\mathrm{<span class="co">[</span><span class="ot">K</span><span class="co">]</span>}$ <span class="pp">|</span></span>
<span id="cb1-463"><a href="#cb1-463" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|---|</span></span>
<span id="cb1-464"><a href="#cb1-464" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 1.0 <span class="pp">|</span> $5\times10^4$ <span class="pp">|</span> $10^{-4}$ <span class="pp">|</span> $0.060$ <span class="pp">|</span></span>
<span id="cb1-465"><a href="#cb1-465" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 1.0 <span class="pp">|</span> $10^5$ <span class="pp">|</span> $10^{-4}$ <span class="pp">|</span> $0.239$ <span class="pp">|</span></span>
<span id="cb1-466"><a href="#cb1-466" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> 1.0 <span class="pp">|</span> $2\times10^5$ <span class="pp">|</span> $10^{-4}$ <span class="pp">|</span> $0.957$ <span class="pp">|</span></span>
<span id="cb1-467"><a href="#cb1-467" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> 2.0 <span class="pp">|</span> $10^5$ <span class="pp">|</span> $10^{-4}$ <span class="pp">|</span> $0.479$ <span class="pp">|</span></span>
<span id="cb1-468"><a href="#cb1-468" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> 1.0 <span class="pp">|</span> $10^5$ <span class="pp">|</span> $10^{-3}$ <span class="pp">|</span> $2.392$ <span class="pp">|</span></span>
<span id="cb1-469"><a href="#cb1-469" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 6 <span class="pp">|</span> 2.0 <span class="pp">|</span> $2\times10^5$ <span class="pp">|</span> $10^{-3}$ <span class="pp">|</span> $19.14$ <span class="pp">|</span></span>
<span id="cb1-470"><a href="#cb1-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-471"><a href="#cb1-471" aria-hidden="true" tabindex="-1"></a>**Interpretación:**</span>
<span id="cb1-472"><a href="#cb1-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-473"><a href="#cb1-473" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>El caso 6 produce el mayor calentamiento ($19.1~\mathrm{K}$), porque combina alta conductividad, campo intenso y pulso largo.</span>
<span id="cb1-474"><a href="#cb1-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-475"><a href="#cb1-475" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Duplicar $E$ cuadruplica $\Delta T$ (casos 2 → 3: $0.239 \times 4 = 0.957~\mathrm{K}$). Duplicar $\sigma$ o $\tau$ solo lo duplica. El campo tiene el mayor efecto relativo.</span>
<span id="cb1-476"><a href="#cb1-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-477"><a href="#cb1-477" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>El campo aparece como $E^2$ porque la potencia disipada $q = \sigma E^2$ ya es cuadrática en $E$: la corriente $J = \sigma E$ y la potencia por unidad de volumen $q = J \cdot E = \sigma E^2$.</span>
<span id="cb1-478"><a href="#cb1-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-479"><a href="#cb1-479" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Un aumento de $\sim 1~\mathrm{K}$ (caso 3) comienza a ser biológicamente relevante si se acumula con múltiples pulsos. El caso 6, con $\sim 19~\mathrm{K}$, sería claramente problemático: podría desnaturalizar proteínas, alterar membranas y comprometer la viabilidad celular.</span>
<span id="cb1-480"><a href="#cb1-480" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-481"><a href="#cb1-481" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Esta estimación no incluye difusión térmica durante el pulso, heterogeneidad del tejido, ni acumulación entre pulsos. En geometrías reales el campo no es uniforme y existen puntos calientes cerca de los electrodos.</span>
<span id="cb1-482"><a href="#cb1-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-483"><a href="#cb1-483" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>Con $N$ pulsos repetidos y sin tiempo suficiente para disipar el calor: $\Delta T_{\mathrm{total}} \approx N \times \Delta T_{\mathrm{pulso}}$. Para frecuencias altas o trenes densos, el calentamiento puede sumarse significativamente.</span>
<span id="cb1-484"><a href="#cb1-484" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-485"><a href="#cb1-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-486"><a href="#cb1-486" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-487"><a href="#cb1-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-488"><a href="#cb1-488" aria-hidden="true" tabindex="-1"></a><span class="fu"># Actividad integradora</span></span>
<span id="cb1-489"><a href="#cb1-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-490"><a href="#cb1-490" aria-hidden="true" tabindex="-1"></a>*Nivel: avanzado*</span>
<span id="cb1-491"><a href="#cb1-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-492"><a href="#cb1-492" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivo</span></span>
<span id="cb1-493"><a href="#cb1-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-494"><a href="#cb1-494" aria-hidden="true" tabindex="-1"></a>Conectar los cuatro módulos del portal en una interpretación biofísica unificada.</span>
<span id="cb1-495"><a href="#cb1-495" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-496"><a href="#cb1-496" aria-hidden="true" tabindex="-1"></a><span class="fu">## Situación problema</span></span>
<span id="cb1-497"><a href="#cb1-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-498"><a href="#cb1-498" aria-hidden="true" tabindex="-1"></a>Se desea aplicar un protocolo de electroporación a células aproximadamente esféricas de radio $a = 10~\mu\mathrm{m}$, en un medio con conductividad $\sigma = 1.2~\mathrm{S/m}$, usando un pulso rectangular de duración $\tau = 100~\mu\mathrm{s}$.</span>
<span id="cb1-499"><a href="#cb1-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-500"><a href="#cb1-500" aria-hidden="true" tabindex="-1"></a>Se evalúan tres protocolos:</span>
<span id="cb1-501"><a href="#cb1-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-502"><a href="#cb1-502" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Protocolo <span class="pp">|</span> $E_0$ <span class="pp">|</span></span>
<span id="cb1-503"><a href="#cb1-503" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-504"><a href="#cb1-504" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> A <span class="pp">|</span> $0.5~\mathrm{kV/cm}$ <span class="pp">|</span></span>
<span id="cb1-505"><a href="#cb1-505" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> B <span class="pp">|</span> $1.0~\mathrm{kV/cm}$ <span class="pp">|</span></span>
<span id="cb1-506"><a href="#cb1-506" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> C <span class="pp">|</span> $2.0~\mathrm{kV/cm}$ <span class="pp">|</span></span>
<span id="cb1-507"><a href="#cb1-507" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-508"><a href="#cb1-508" aria-hidden="true" tabindex="-1"></a><span class="fu">## Preguntas orientadoras</span></span>
<span id="cb1-509"><a href="#cb1-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-510"><a href="#cb1-510" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Estime $\Delta V_m^{\mathrm{ind}}$ en los polos para cada protocolo.</span>
<span id="cb1-511"><a href="#cb1-511" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>¿Cuál protocolo podría superar el umbral aproximado de $1~\mathrm{V}$?</span>
<span id="cb1-512"><a href="#cb1-512" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>¿Cómo cambiaría cualitativamente la barrera energética $\Delta G_c$ al pasar del protocolo A al C?</span>
<span id="cb1-513"><a href="#cb1-513" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Estime $\Delta T$ para cada protocolo.</span>
<span id="cb1-514"><a href="#cb1-514" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>¿Cuál protocolo parece más favorable para inducir permeabilización con calentamiento moderado?</span>
<span id="cb1-515"><a href="#cb1-515" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>¿Por qué la decisión experimental no debe basarse solo en una ecuación?</span>
<span id="cb1-516"><a href="#cb1-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-517"><a href="#cb1-517" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb1-518"><a href="#cb1-518" aria-hidden="true" tabindex="-1"></a><span class="fu">## 💡 Pista — Actividad integradora</span></span>
<span id="cb1-519"><a href="#cb1-519" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-520"><a href="#cb1-520" aria-hidden="true" tabindex="-1"></a>Esta actividad une los resultados de las cuatro anteriores. Aplica cada modelo por separado y luego compara:</span>
<span id="cb1-521"><a href="#cb1-521" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-522"><a href="#cb1-522" aria-hidden="true" tabindex="-1"></a>**Voltaje inducido:** usa $\Delta V_m^{\mathrm{ind}} = 1.5 \times a \times E_0$ con $a = 10^{-5}~\mathrm{m}$.</span>
<span id="cb1-523"><a href="#cb1-523" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-524"><a href="#cb1-524" aria-hidden="true" tabindex="-1"></a>**Barrera energética:** no es necesario calcularlo numéricamente. Razona cualitativamente: al aumentar $V_m^{\mathrm{tot}}$, el denominador $A = \pi\Gamma + kV^2$ crece, y $\Delta G_c = \pi^2\gamma^2/A$ disminuye.</span>
<span id="cb1-525"><a href="#cb1-525" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-526"><a href="#cb1-526" aria-hidden="true" tabindex="-1"></a>**Calentamiento:** usa $\Delta T = \sigma E^2 \tau / (\rho c_p)$ con $\sigma = 1.2~\mathrm{S/m}$, $\tau = 10^{-4}~\mathrm{s}$, $\rho c_p = 4.18\times10^6~\mathrm{J\,m^{-3}\,K^{-1}}$.</span>
<span id="cb1-527"><a href="#cb1-527" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-528"><a href="#cb1-528" aria-hidden="true" tabindex="-1"></a>El protocolo B suele ser el punto de equilibrio típico: campo suficiente para inducir permeabilización, calentamiento aún moderado. Verifica los números antes de concluir.</span>
<span id="cb1-529"><a href="#cb1-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-530"><a href="#cb1-530" aria-hidden="true" tabindex="-1"></a>Para la pregunta 6, reflexiona sobre qué aspecto **no** cubre cada modelo por separado.</span>
<span id="cb1-531"><a href="#cb1-531" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-532"><a href="#cb1-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-533"><a href="#cb1-533" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb1-534"><a href="#cb1-534" aria-hidden="true" tabindex="-1"></a><span class="fu">## ✓ Respuesta — Actividad integradora</span></span>
<span id="cb1-535"><a href="#cb1-535" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-536"><a href="#cb1-536" aria-hidden="true" tabindex="-1"></a>**1. Voltaje transmembrana inducido en los polos** ($a = 10^{-5}~\mathrm{m}$, $f = 1.5$):</span>
<span id="cb1-537"><a href="#cb1-537" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-538"><a href="#cb1-538" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Protocolo <span class="pp">|</span> $E_0~\mathrm{<span class="co">[</span><span class="ot">V/m</span><span class="co">]</span>}$ <span class="pp">|</span> $\Delta V_m^{\mathrm{ind}}~\mathrm{<span class="co">[</span><span class="ot">V</span><span class="co">]</span>}$ <span class="pp">|</span></span>
<span id="cb1-539"><a href="#cb1-539" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-540"><a href="#cb1-540" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> A <span class="pp">|</span> $5\times10^4$ <span class="pp">|</span> $0.75$ <span class="pp">|</span></span>
<span id="cb1-541"><a href="#cb1-541" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> B <span class="pp">|</span> $10^5$ <span class="pp">|</span> $1.50$ <span class="pp">|</span></span>
<span id="cb1-542"><a href="#cb1-542" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> C <span class="pp">|</span> $2\times10^5$ <span class="pp">|</span> $3.00$ <span class="pp">|</span></span>
<span id="cb1-543"><a href="#cb1-543" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-544"><a href="#cb1-544" aria-hidden="true" tabindex="-1"></a>**2.** Solo los protocolos B y C superan el umbral de $1~\mathrm{V}$. El protocolo A ($0.75~\mathrm{V}$) queda por debajo, lo que sugiere permeabilización subumbral o muy débil.</span>
<span id="cb1-545"><a href="#cb1-545" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-546"><a href="#cb1-546" aria-hidden="true" tabindex="-1"></a>**3. Barrera energética** (razonamiento cualitativo): al pasar de A a C, $V_m^{\mathrm{tot}}$ crece cuatro veces, el término $kV^2$ en el denominador aumenta notablemente y $\Delta G_c$ disminuye de forma significativa. Con $V \approx 0.75~\mathrm{V}$ (protocolo A) la barrera es alta; con $V \approx 1.5~\mathrm{V}$ (protocolo B) cae a valores comparables a las fluctuaciones térmicas; con $V \approx 3.0~\mathrm{V}$ (protocolo C) la nucleación sería prácticamente espontánea.</span>
<span id="cb1-547"><a href="#cb1-547" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-548"><a href="#cb1-548" aria-hidden="true" tabindex="-1"></a>**4. Calentamiento Joule** ($\sigma = 1.2~\mathrm{S/m}$, $\tau = 10^{-4}~\mathrm{s}$):</span>
<span id="cb1-549"><a href="#cb1-549" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-550"><a href="#cb1-550" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-551"><a href="#cb1-551" aria-hidden="true" tabindex="-1"></a>\Delta T = \frac{1.2 \times E^2 \times 10^{-4}}{4.18\times10^6}</span>
<span id="cb1-552"><a href="#cb1-552" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-553"><a href="#cb1-553" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-554"><a href="#cb1-554" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Protocolo <span class="pp">|</span> $E~\mathrm{<span class="co">[</span><span class="ot">V/m</span><span class="co">]</span>}$ <span class="pp">|</span> $\Delta T~\mathrm{<span class="co">[</span><span class="ot">K</span><span class="co">]</span>}$ <span class="pp">|</span></span>
<span id="cb1-555"><a href="#cb1-555" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-556"><a href="#cb1-556" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> A <span class="pp">|</span> $5\times10^4$ <span class="pp">|</span> $0.072$ <span class="pp">|</span></span>
<span id="cb1-557"><a href="#cb1-557" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> B <span class="pp">|</span> $10^5$ <span class="pp">|</span> $0.287$ <span class="pp">|</span></span>
<span id="cb1-558"><a href="#cb1-558" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> C <span class="pp">|</span> $2\times10^5$ <span class="pp">|</span> $1.148$ <span class="pp">|</span></span>
<span id="cb1-559"><a href="#cb1-559" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-560"><a href="#cb1-560" aria-hidden="true" tabindex="-1"></a>**5.** El protocolo B es el más equilibrado: supera el umbral de voltaje inducido ($1.5~\mathrm{V}$), reduce la barrera energética a valores donde la nucleación es probable, y produce un calentamiento de solo $\sim 0.29~\mathrm{K}$ por pulso. El protocolo C favorece más la permeabilización, pero el calentamiento de $\sim 1.1~\mathrm{K}$ por pulso puede acumularse con múltiples pulsos.</span>
<span id="cb1-561"><a href="#cb1-561" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-562"><a href="#cb1-562" aria-hidden="true" tabindex="-1"></a>**6.** Ninguna ecuación es suficiente sola:</span>
<span id="cb1-563"><a href="#cb1-563" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-564"><a href="#cb1-564" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Modelo <span class="pp">|</span> Lo que no incluye <span class="pp">|</span></span>
<span id="cb1-565"><a href="#cb1-565" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-566"><a href="#cb1-566" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Schwan ($\Delta V_m^{\mathrm{ind}}$) <span class="pp">|</span> Dinámica temporal, heterogeneidad celular, geometría no esférica <span class="pp">|</span></span>
<span id="cb1-567"><a href="#cb1-567" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> RC (carga temporal) <span class="pp">|</span> Distribución espacial del voltaje, efectos no lineales <span class="pp">|</span></span>
<span id="cb1-568"><a href="#cb1-568" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Energía del poro ($\Delta G_c$) <span class="pp">|</span> Barrera hidrofóbica, fluctuaciones estocásticas, cierre del poro <span class="pp">|</span></span>
<span id="cb1-569"><a href="#cb1-569" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Calentamiento Joule ($\Delta T$) <span class="pp">|</span> Difusión térmica, acumulación de pulsos, geometría del electrodo <span class="pp">|</span></span>
<span id="cb1-570"><a href="#cb1-570" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-571"><a href="#cb1-571" aria-hidden="true" tabindex="-1"></a>El diseño racional de un protocolo requiere integrar todos estos aspectos: el campo debe ser suficiente para inducir voltaje y reducir la barrera, el pulso debe ser suficientemente largo para cargar la membrana, y el calentamiento acumulado debe mantenerse dentro de límites biológicamente tolerables.</span>
<span id="cb1-572"><a href="#cb1-572" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-573"><a href="#cb1-573" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-574"><a href="#cb1-574" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-575"><a href="#cb1-575" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-576"><a href="#cb1-576" aria-hidden="true" tabindex="-1"></a><span class="fu"># Cierre</span></span>
<span id="cb1-577"><a href="#cb1-577" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-578"><a href="#cb1-578" aria-hidden="true" tabindex="-1"></a>Estas actividades muestran que la electroporación no depende de un único parámetro. La respuesta celular surge de la interacción entre la geometría celular, la intensidad del campo eléctrico, la duración del pulso, la dinámica capacitiva de la membrana, la barrera energética para formar poros y la disipación Joule en el medio.</span>
<span id="cb1-579"><a href="#cb1-579" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-580"><a href="#cb1-580" aria-hidden="true" tabindex="-1"></a>Por ello, el diseño racional de protocolos de electroporación requiere combinar modelos eléctricos, térmicos y biofísicos.</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>